/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myproj_first_MainActivity */

#ifndef _Included_com_myproj_first_MainActivity
#define _Included_com_myproj_first_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myproj_first_MainActivity
 * Method:    getMyData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myproj_first_MainActivity_getMyData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
